### ISSUE TITLE
Serialize Adding Quotes to key values when not needed

### ISSUE THREAD

**Issue by knightzac19** [Ajnasz/IniReader#11]
So I realize that the serialize function has the quotes there to protect values, but in my case that actually does more harm then good.

For example it added quotes around these,

```
DinoSpawnWeightMultipliers='(DinoNameTag="Elite Carno",SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=True,SpawnLimitPercentage=5)'
DinoSpawnWeightMultipliers='(DinoNameTag="Elite Raptor",SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=True,SpawnLimitPercentage=5)'
DinoSpawnWeightMultipliers='(DinoNameTag="Elite Rex",SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=True,SpawnLimitPercentage=3)'
```

and they didn't need any quotes at all.

Then there's this one,

```
Message="Test my Message!"
```

Where I understand why it added quotes, but in this case I'd need a way to tell the serialize function I don't want quotes in there. Preferably per variable because I do have atleast one variable that needs quotes because it's a URL.

**Comment by Ajnasz** [comment]
Yes quoting is very dummy, I will try to find a better solution

**Comment by Ajnasz** [comment]
Could you please take a look at 79b684e?

What i changed:
Quote only values which starts or ends with white space characters.
  In that case 
>     Quote into single quotes (') if the value does not contain single quote
>     char (');
>     Quote into double quotes if value contains at least one single quote
>     character.
>         Escape double quotes with backslash (\) if value contains at least one
>         single quote character.

It may still have issue with more advanced escapes in values (if starts/ends with quotes)

**Comment by knightzac19** [comment]
Works good, but I noticed that if I had anything in the INI that had quotes around it (because it needed it) the parser.write(); removed the quotes afterwards.

This is the key that it's removing the quotes from.
```
BanListURL="http://playark.com/banlist.txt"
```

**Comment by Ajnasz** [comment]
Why do you need quotes there?

**Comment by knightzac19** [comment]
The game can't parse the URL properly without them sadly :/

**Comment by Ajnasz** [comment]
I fixed it in 2bc2829 because I can consider this behavior as data loss.

However, I would fix the URL parser or quote the URL when it's needed. For human eyes it's not trivial why you want a double quote there.

**Comment by knightzac19** [comment]
Sorry I got back so late, but it's still not writing back the quotes to the INI file.

As far as the parser, it's part of Unreal Engine, can't really do much about that either. :(

**Comment by Ajnasz** [comment]
78fbb4c may can help:
```javascript
new IniReader({
	hooks: {
		write: {
			keyValue: function (keyValue, group) {
				if (group === 'ServerSettings' && keyValue[0] === 'BanListURL') {
				keyValue[1] = '"' + keyValue[1] + '"';
				}

				return keyValue;
			}
		}
	}
});
```

**Comment by zknightfsw** [comment]
So now this
```
parser.param(['ServerSettings',"BanListURL"],'"http://playark.com/banlist.txt"');
```
returns
```
BanListURL='"http://playark.com/banlist.txt"'
```
and your hook does this,
```
BanListURL="'"http://playark.com/banlist.txt"'"
```

So for your testing, just so you can figure all this out, the variable is supposed to look like this in the INI,
```
BanListURL="http://playark.com/banlist.txt"
```

Found a small bug while testing some things.

This here (I know it's not right, but the error isn't handled),
```
console.log(parser.param(['ServerSettings',"BanListURL"]));
```
throws this error,
```
TypeError: param.split is not a function
    at findValidBlock (H:\Github Projects\nodejs\node_modules\inireader\lib\inireadercore.js:435:22)
    at IniReaderCore.getParam (H:\Github Projects\nodejs\node_modules\inireader\lib\inireadercore.js:473:17)
    at IniReaderCore.param (H:\Github Projects\nodejs\node_modules\inireader\lib\inireadercore.js:541:23)
    at Object.<anonymous> (H:\Github Projects\nodejs\lib\serverconfig.js:47:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

**Comment by knightzac19** [comment]
So now this
```
parser.param(['ServerSettings',"BanListURL"],'"http://playark.com/banlist.txt"');
```
returns
```
BanListURL='"http://playark.com/banlist.txt"'
```
and your hook does this,
```
BanListURL="'"http://playark.com/banlist.txt"'"
```

So for your testing, just so you can figure all this out, the variable is supposed to look like this in the INI,
```
BanListURL="http://playark.com/banlist.txt"
```

Found a small bug while testing some things.

This here (I know it's not right, but the error isn't handled),
```
console.log(parser.param(['ServerSettings',"BanListURL"]));
```
throws this error,
```
TypeError: param.split is not a function
    at findValidBlock (H:\Github Projects\nodejs\node_modules\inireader\lib\inireadercore.js:435:22)
    at IniReaderCore.getParam (H:\Github Projects\nodejs\node_modules\inireader\lib\inireadercore.js:473:17)
    at IniReaderCore.param (H:\Github Projects\nodejs\node_modules\inireader\lib\inireadercore.js:541:23)
    at Object.<anonymous> (H:\Github Projects\nodejs\lib\serverconfig.js:47:21)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

**Comment by Ajnasz** [comment]
You don't need to quote yourself, the hook will quote where you want. Or alternatively you can change the code in the hook to match your needs.

So, I recommend to do this instead:
`parser.param(['ServerSettings',"BanListURL"],'http://playark.com/banlist.txt');`

Fix for the error committed in 03cb08c654933f9888a0
